Improve Neovim build; add test structure
1. Manually remove LUA_PATH before building Neovim. Then I can add
   a LUA_PATH to my shell environment.
2. Stub out a simple way to run tests on my Neovim code.

diff --git a/bin/neoup b/bin/neoup
--- a/bin/neoup
+++ b/bin/neoup
@@ -27,16 +27,16 @@ fi
 cd "$BUILD_FULL" || die "$(printf '`cd %s` failed' "$BUILD_FULL")"
 git pull || die '`git pull` failed'
 
-if [ X"${1:-}" = X"--clean" ]; then
+if [ "${1:-}" = "--clean" ]; then
     make distclean || die '`make distclean` failed'
 fi
-make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX="$INSTALL_DIR" ||
-    die '`make` failed'
+LUA_PATH='' LUA_CPATH='' make CMAKE_BUILD_TYPE=Release \
+    CMAKE_INSTALL_PREFIX="$INSTALL_DIR" || die '`make` failed'
 rm -rf "$INSTALL_DIR" || die "$(printf '`rm -rf %s` failed' "$INSTALL_DIR")"
-make install || die '`make install` failed'
+LUA_PATH='' LUA_CPATH='' make install || die '`make install` failed'
 
 # Update plugins and their helptags.
-pluggo -config=${HOME}/.config/nvim/nvim-pluggo.json || die 'pluggo failed'
+pluggo -config="${HOME}"/.config/nvim/nvim-pluggo.json || die 'pluggo failed'
 nvim --headless -c 'helptags ALL | quit' || die 'failed to update helptag files'
 
 # vim: set ts=8 sw=4 ts=4 tw=0 et ft=sh :
